language: ruby
rvm: 2.7.0
cache: bundler
before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
script: bundle exec ruby _scripts/memprof.rb
env:
  - TRACE_CLASS="String"
  - TRACE_CLASS="Array" ALLOW_FILES="lib/jekyll/"
  - TRACE_CLASS="Hash"
  - TRACE_CLASS="Regexp"
  - ALLOW_FILES="lib/jekyll/"
notifications:
  email: false
