language: ruby
rvm: 2.7.0
cache: bundler
before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
script: bundle exec ruby _scripts/methprof.rb
env:
  - KLASS="Jekyll::Page"
  - KLASS="Jekyll::Document"
  - KLASS="Jekyll::StaticFile"
  - KLASS="Jekyll::Convertible"
  - KLASS="Jekyll::Drops::Drop"
  - KLASS="Jekyll::URL"
notifications:
  email: false
