language: ruby
rvm: 2.7.0
cache: bundler
before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
  - bundle config gemfile _jekyll/Gemfile
  - bundle config path vendor/bundle
script: bundle exec ruby _scripts/memprof.rb
notifications:
  email: false
