name: Continuous Integration

on: [push]

jobs:
  build:
    name: Jekyll 4 build (Ruby ${{ matrix.ruby }})

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.2"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    env:
      BUNDLE_GEMFILE: "sandbox/Gemfile"
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3

    steps:
      - name: Dump environment
        run: env | sort
      - name: Checkout ruby/www.ruby-lang.org
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: sandbox
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Dump Ruby version
        run: ruby -v
      - name: Build with Jekyll
        run: bundle exec jekyll build -s sandbox -d sandbox/_site --profile
